### Add user
POST http://localhost:3000/users 
content-type: application/json

{
  "username": "test",
  "email": "t@test.com",
  "password": "123452"
}

### Confirm user Email
PUT http://localhost:3000/users/emailconfirm/62a63c74973b7963b5a3b4d8

### Signin
POST http://localhost:3000/users/signin
content-type: application/json

{
  "email": "t@test.com",
  "password": "123452"
}

### Signout
POST http://localhost:3000/users/signout
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYyYTRkYzFiMjMxZTg3YzQ3N2I4ZGMyOSIsInVzZXJuYW1lIjoiYXNhc2RkZiIsImVtYWlsIjoiYUBhc2FzZC5jb20iLCJwYXNzd29yZCI6IjEyMzQ1MiIsImNvbmZpcm1lZEF0IjoiMTEtMDYtMjAyMiAyMToxNyIsIl9fdiI6MH0sImlhdCI6MTY1NTA1MTUwOCwiZXhwIjoxNjU1MDU1MTA4fQ.zZdZr2NGyjuzlHZc9DjI5l2jAu5EZimoq6k4lAy-Cxs

